config/routes.rb
Rails.application.routes.draw do
  devise_for :users,controllers: {
                 sessions: 'users/sessions',
                 registrations: 'users/registrations'
             }
  get 'comments/new'
  get 'comments/create'
  get 'likes/create'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'
  resources :users, only: [:index, :show ] do 
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [ :create, :destroy]
    resources :likes, only: [:create ]
  end 
end
# namespace :api, defaults: { format: :json } do
#   namespace :v1 do
#   resources :users, only: [:index] do 
#     resources :posts, only: [:index] do
#       resources :comments, only: [:index] 
#      end
#     end
#   end
#   end

namespace :api do 
  namespace :v1 do 
    resources :users, only: %i[create index] do 
      resources :posts, only: %i[index show] do 
        resources :comments, only: %i[index new create ] 
      end 
    end 
  end 
end 
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :likes, class_name: 'Like', foreign_key: :post_id, dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: :post_id, dependent: :destroy
  # validations

  validates :Title, presence: true, length: { maximum: 250 }
  validates :Comments_Counter, :Likes_Counter, numericality: { only_integer: true },
                                               comparison: { greater_than_or_equal_to: 0 }

  def recent_comments
    comments.limit(5).order(created_at: :desc)
  end

  after_save :update_post_counter

  def update_post_counter
    author.increment!(:Posts_Counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @post = @user.posts
    render json: @post, status: :ok
  end

  def show
    @post = Post.find(params[:id])
    render json: @post, status: :ok
  end
end

app/controllers/posts_controller.rb
# before_action :set_post, only: [:index, :show, :destroy]

class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    @user_posts = @user.posts.includes(:author)
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comment = Comment.new
    @like = Like.new
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    puts 'Yes I can destroy'
    @post.destroy
    redirect_to user_post_path(@user.id, @post.id)
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
    @params = params
  end

  def create
    @user = User.find(params[:user_id])
    @post = current_user.posts.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to user_posts_url(@user.id) }
      else
        format.html { render :new }
      end
    end
  end

  private

  def post_params
    params.require(:post).permit(:Title, :Text, :author_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<%= render partial: 'partials/user', locals: { user: @user } %>
<%  @user_posts.each do |post| %>
    <%= render partial: 'partials/post', locals: { post: post} %>
      <ul class="comments">
      <% post.recent_comments.each do |comment| %>
        <li><%= comment.author.Name %>: <%= comment.text %>
      <% end %>
      </ul>
<% end %>
<%= link_to "Add new post", new_user_post_path(@user), class: "see-all-btn" %>

app/views/posts/new.html.erb
<%= form_for @post, url: user_posts_path(@user.id) do |f| %>
  <h2>CREATE A NEW POST</h2>
    <% if @post.errors.any? %>
      <ul class="errors">
        <% @post.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    <% end %>
    <%= f.hidden_field :author_id, value: @params ? @params['user_id'] : '' %>
    <div  class: 'article_title'>
     <%= f.label :Title %><br /> 
      <%= f.text_field :Title, placeholder: 'Article title'%>
    </div>
    <div>
      <%= f.label :Text, "Description" %><br />
      <%= f.text_area :Text, placeholder: 'Type your article message in here...' %>
    </div>
    <%= f.submit "Submit post", disable_with: 'Submiting...' %>
  <% end %> 

app/views/posts/show.html.erb
<article class="post-snipet">
    
    <h3><%= @post.Title %>  by <%= link_to @post.author.Name, user_path(@post.author_id) %></h3>
    <div class="post-stats">
      <span>Comments <%= @post.Comments_Counter %> &nbsp;,&nbsp;</span>
      <span>Likes <%= @post.Likes_Counter %></span>
    </div>
    <p><%= @post.Text %></p>
  </article>
  <%= form_for @like, url: user_post_likes_path(@user.id, @post.id) do |f|%>
    <%= f.hidden_field :author_id, value: @post.author.id %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.submit "Like", class:'btn', disable_with: 'updating likes...' %>
  <% end %>
  <ul class="comments">
    <% @post.recent_comments.includes(:author).each do |comment| %>
      <li><%= comment.author.Name %>: <%= comment.text %>
      <% if can? :destroy, comment %>
      <div><%= button_to 'Delete', user_post_comment_path(@user.id, @post.id, comment.id), method: :delete %></div>
  <% end %>
    <% end %>
    
  </ul> 
  <h4> ADD COMMENT </h4>
  <%= form_for @comment, url: user_post_comments_path(@user.id, @post.id) do |f| %>
    <%= f.hidden_field :author_id, value: @post.author.id %>
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.text_area :text, placeholder:'What are your thoughts on this post?' %><br />
    <%= f.submit "Submit comment", class:"btn see-all-btn", disable_with: 'Submiting Comment...' %>
  <% end %>